# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b039ec31c3ac7c8d04292f9836631c50a1ba7f6392ebffbecc19c43a81a9c6122a0f7e4c807162918476b7689b8f72bf0830ab283aaedbf8463d660e41a3e0d7

test:
  secret_key_base: 63de754622acf973f1768d52a89b386b2641d0bf3270f8793d71f219abf29b5af96cb323a2d15ce32b21ccfac4bb1761f035f8f3d4a2ca23becf305e1b7a1495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
